[tool.poetry]
name = "taichi2dfluidsim"
version = "0.1.0"
description = ""
authors = ["tifufu <dematasjoshua@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.9"
taichi = "^1.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
